### ISSUE TITLE
Is <buffer> implemented?

### ISSUE THREAD

**Issue by itchyny** [kana/vim-altercmd#1]
The document says `If <buffer> is given, this declaration is only available for the current buffer.` but it does not seem that this feature is implemented.

**Comment by itchyny** [comment]
Wow, thank you! I confirmed that it works well.

Is there a possibility that you would accept a new feature request?
I really want `<silent>` flag, that I can hide the mapped commands.
I would like to give `'<silent>'` for the first argument of `altercmd#define`:

``` vim
" new feature that I want
altercmd#define('<silent>', {original}, {alternative})
" or if possible
altercmd#define('<buffer><silent>', {original}, {alternative})
```

and the corresponding feature for the command; `:AlterCommand <silent> {original}  {alternative}`.
Should I open a new issue?

**Comment by kana** [comment]
It seems to be useless to specify `<silent>` for Command-line mode abbreviations because intermediate mappings shown in the command-line are overwritten by the new command-line to be edited.  Please open a new issue and write a concrete example to describe how it is useful.
