### ISSUE TITLE
Please support <silent>

### ISSUE THREAD

**Issue by itchyny** [kana/vim-altercmd#4]
I want this plugin to support `<silent>`.

``` vim
" new feature that I want
altercmd#define('<silent>', {original}, {alternative})
" or
altercmd#define('<buffer><silent>', {original}, {alternative})
```
## Reasoning 1

I want to deal with the alt-commands just like as the internal commands.
For example, I use the following setting.

``` vim
call altercmd#define('w!!', 'w !sudo tee > /dev/null %')
```

The command `:w` writes the file, `:w!` even if the file is `readonly`, and `:w!!` when we write with `sudo`.
The current altercmd does not use `<silent>` so the command line is replaced with `:w !sudo tee > /dev/null %`, but this is not cool. **The alter-commands should behave like the internal commands.** I want to keep the original text what I typed in the command line.
## Reasoning 2

For echoing alter-commands, the command line flickers twice.
Consider the following configuration

``` vim
call altercmd#define('date', 'echo strftime(''%x (%a) %X'')')
```

When I type `:date<CR>`, the command line is firstly replaced by `echo strftime('%x (%a) %X')`, and then the date is echoed. The command line is replaced twice, it's too annoying.

**Comment by kana** [comment]
No.  The purpose of vim-altercmd is to replace Ex command name.  Your usage is wrong.
Additionally, vim-altercmd is based on abbreviation.  It's not possible to support `<silent>`.

**Comment by itchyny** [comment]
Fine, thanks for your explanation. This plugin potentially enables me to define many shortcuts to call autoload functions that I do not want type every time. It's just useful except for the complaint I wrote in this issue. But it seems that the way I used the plugin was out of the purpose. Thank you.
